### PR TITLE
allow spaces in titles and deprecate slug

### PR DESCRIPTION
**Pull request by brandonjank**
Since we want to support spaces in project titles, this is the easiest way to do it. For the sake of simplicity we'll just have to deal with %20's in the URL.

### CODE REVIEW

**Comment by brandonjank** [comment]
@brec9824 @rickbau5 

Seems to be working properly now. No more wonky hyphen replacement for spaces.

**Comment by brandonjank** [comment]
fixes issue #81 and is related to issue #73

**Comment by brandonjank** [comment]
@brec9824 @rickbau5 

One of you want to merge this?

**Comment by rickbau5** [comment]
merging

**Pull request merged**
