### PR TITLE
Create and View Projects

### PR DESCRIPTION
**Pull request by rickbau5**
Implement Projects:
- New model: `Project` in `projects` table. Fields: title, author, descriptions, body, create & modified
- Create Projects (`/create`) - "Start a New Project" nav element now works!
- View Projects (`/project/{id}`)
- Project Finder uses real projects and their attributes for display!
- Migration for project table: `php artisan migrate`
- Command for some test entries: `php artisan console:PopulateProjectsTable`

Still needed:
- Tests (?)
- Edit projects
- Delete projects
- All the other project stuff (i.e. social)

This will be ongoing, but wanted to get it in for demoing tomorrow. Fairly thoroughly debugged from my end, should be good.

### CODE REVIEW

**Comment by rickbau5** [comment]
I had a thought, I should refactor this to all use "Project Ideas" sort of names for the db and model and such. So don't merge this till I do this. But still good to demo this in class

**Comment by brandonjank** [comment]
Im thinking:
/project/someproject/files/blah.java
would open a file for editing
/project/someproject/
would open the project info (ideas) page.

**Comment by brandonjank** [comment]
Tested and working after `php artisan migrate` and `php artisan console:PopulateProjectsTable` . Merging.

**Comment by rickbau5** [comment]
Cool. That format sounds good to me

**Pull request merged**
