### PR TITLE
Authentication pages html and css changes for displaying errors

### PR DESCRIPTION
**Pull request by brec9824**
Corrected pages the dealt with authentication by fixing error formatting/style/text, fixed forms not scaling appropriately when there is errors, and changed password reset routing from a page that didn't exist to projectfinder.

### CODE REVIEW

**Comment by brandonjank** [comment]
It should be set to MAIL_Driver=mail if you want e-mails to be sent. No
need to change other settings with the simple php mail driver.

**Comment by rickbau5** [comment]
Status? @backburn @brec9824

**Comment by brec9824** [comment]
I changed the title and info because this doesn't effect Issue #7. This is just some cleanup on the html and css because the errors messages were messing up some of the pages. Just minor changes and all works.

**Comment by brandonjank** [comment]
I verified that sendmail is installed and php is configured to use it. Try MAIL_Driver=sendmail in your .env

**Comment by brandonjank** [comment]
Looks good, tested and working. Squash merged and branch deleted.

**Pull request merged**
